name: uni_map_platform_interface
description: Uni Map Platform Interface.
version: 0.7.0
publish_to: none

environment:
  sdk: '>=3.6.2 <4.0.0'
  flutter: '>=3.27.4'

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify:
    # path: ../foundation_fluttify
    git: https://github.com/boomcx/foundation_fluttify
  core_location_fluttify:
    # path: ../core_location_fluttify
    git: https://github.com/boomcx/core_location_fluttify

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
